require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
pod 'RNSound', :path => '../node_modules/react-native-sound'

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'BoxsuApp' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])
end
